# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snapkitList' do
pod 'Alamofire'
pod 'SnapKit'
pod 'Then'
pod 'Kingfisher'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snapkitList

  target 'snapkitListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'snapkitListUITests' do
    # Pods for testing
  end

end
